[project]
name = "preprocessing-challenge"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.3",
    "marimo[recommanded]>=0.18.4",
    "polars>=1.36.1",
    "scikit-learn>=1.8.0",
]

[tool.uv]
cache-dir = './.cache'
